/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package horus;

public class App {
    public static void main(String[] args) {
        DynamicList<String> list = new DynamicList<>();

        for(int i = 0; i < 11; i++)
            list.push_back(String.format("%d", i));

        list.push_front("Horus");
        list.add("Thiago", 4);
        list.remove(4);
        list.add("Rezende", 4);
        list.pop_back();
        list.pop_front();

        System.out.println(list);
    }
}
