/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package horus;

import org.json.JSONObject;
import java.util.Scanner;

public class App {
    public static void main(String[] args)
    {
        UserList usr_list = new UserList();
        Scanner in = new Scanner(System.in);
        int opt;

        while(true)
        {
            show_menu();
            System.out.print("In > ");
            opt = in.nextInt();

            switch(opt)
            {
                case 1:
                    usr_list.read_file("test.txt");
                    break;
                case 2:
                    usr_list.show_users();
                    break;
                case 3:
                    System.out.print("name > ");
                    usr_list.show_user(in.next());
                    break;
                case 4:
                    System.out.print("time > ");
                    usr_list.show_usersAfterTime(in.nextInt());
                    break;
                case 5:
                    System.out.print("time > ");
                    usr_list.remove_usersBeforeTime(in.nextInt());
                    break;
                case 6:
                    usr_list.sortByName();
                    break;
                case 7:
                    usr_list.sortByUsage();
                    break;
                case 8:
                    show_json(usr_list);
                    break;
                case 9:
                    System.exit(0);
                    break;
                default:
                    break;
            }
        }

    }

    public static void show_menu()
    {
        String menu =
        " ======= Testing Suit =======     \n" +
        " 1 - Read File                    \n" +
        " 2 - Show All Users               \n" +
        " 3 - Show an User                 \n" +
        " 4 - Show Users After a Time      \n" +
        " 5 - Remove Users Before a Time   \n" +
        " 6 - Sort by Name                 \n" +
        " 7 - Sort by Usage                \n" +
        " 8 - Show JSON                    \n" +
        " 9 - Exit                         \n";

        System.out.println(menu);
    }

    public static void show_json(UserList usr_list)
    {
        JSONObject jobj = new JSONObject(usr_list.toString());
        System.out.println(jobj.toString(2));
    }
}
