/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package horus;

import org.json.JSONObject;
import java.io.File;
import java.util.Scanner;
import java.io.FileNotFoundException;

public class App {
    public static void main(String[] args)
    {
        UserList usr_lst = new UserList();
        LoginTime login = new LoginTime(5, 10);
        LoginTime login1 = new LoginTime(7, 20);
        User usr = new User("Horus");
        User usr1 = new User("Aorus");
        usr.add_login(login);
        usr1.add_login(login1);
        usr_lst.add_user(usr);
        usr_lst.add_user(usr1);
        usr_lst.sortByName();
        usr_lst.sortByUsage();
        System.out.println(usr_lst);
        usr_lst.remove_usersBeforeTime(8);
        System.out.println(usr_lst);
        File data;
        Scanner in;
        String code;
        User usuario;
        LoginTime lg_time;
        try{
            data = new File("test.txt");
            in = new Scanner(data);

            while (in.hasNext()) {
                usuario = new User();
                lg_time = new LoginTime(0, 0);
                usuario.set_name(in.next());
                lg_time.set_loginTime(in.nextInt());
                lg_time.set_logoutTime(in.nextInt());
                usuario.add_login(lg_time);
                usr_lst.add_user(usuario);
            }
            in.close();
        }
        catch(FileNotFoundException e){
            System.out.println(e);
        }

        JSONObject jobj = new JSONObject(usr_lst.toString());
        System.out.println(jobj.toString(2));

    }
}
